version: '3.3'

services:
  text-classifier: 
    build: 
      context: ./serve
      dockerfile: Dockerfile
    container_name: text-classifier
    environment:
      - MODEL_PATH=model.p
    restart: unless-stopped
    ports: 
      - "8080:8080"